# FRONT DOOR
- platform: generic
  still_image_url: !secret front_door_url
  name: Front Door
  username: !secret tplink_user
  password: !secret tplink_password

# GATE
- platform: generic
  still_image_url: !secret north_gate_url
  name: Gate
  username: !secret tplink_user
  password: !secret tplink_password

# NORTH PTZ
- platform: generic
#- platform: amcrest
  still_image_url: !secret north_ptz_url
#  host: 192.168.11.100
#  port: 8083
  name: North PTZ
#  resolution: low
  username: !secret tplink_user
  password: !secret tplink_password

# Kitchen PTZ
- platform: generic
#- platform: amcrest
  still_image_url: !secret kitchen_ptz_url
#  host: 192.168.11.101
#  port: 8084
  name: Kitchen PTZ
#  resolution: low
  username: !secret tplink_user
  password: !secret tplink_password