## FRONT DOOR
- platform: generic
  still_image_url: !secret front_door_url
  name: Front Door
  username: !secret tplink_user
  password: !secret tplink_password

## GATE
- platform: generic
  still_image_url: !secret north_gate_url
  name: Gate
  username: !secret tplink_user
  password: !secret tplink_password

### Amcrest (not working as well as generic...test that again)
## NORTH PTZ
- platform: generic
  still_image_url: !secret north_ptz_url
  name: North PTZ
  username: !secret tplink_user
  password: !secret tplink_password

## KITCHEN PTZ
- platform: generic
  still_image_url: !secret kitchen_ptz_url
  name: Kitchen PTZ
  username: !secret tplink_user
  password: !secret tplink_password