homeassistant:
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: 387
  unit_system: imperial
  time_zone: America/Phoenix

#####################################################################
### CUSTOMIZATION
#####################################################################
  customize: !include customize.yaml
  packages: !include_dir_named packages
  customize_glob: !include customize_glob.yaml
#  customize_domain:

#####################################################################
### ZONE CONFIG
#####################################################################
zone 1:
  name: Rick Work
  latitude: !secret latitude_rick_work
  longitude: !secret longitude_rick_work
  radius: 350
  icon: mdi:briefcase

zone 2:
  name: Megs Work
  latitude: !secret latitude_megs_work
  longitude: !secret longitude_megs_work
  radius: 150
  icon: mdi:school

#####################################################################
### SERVICES CONFIG
#####################################################################
mqtt:
  broker: !secret broker
  port: 1883
  client_id: home-assistant-100
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password

ifttt:
  key: !secret ifttt_api_key

#####################################################################
### ZWAVE CONFIG
#####################################################################
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  polling_interval: 40000

## 0.39 syntax ###
## Device config
  device_config_domain:
    lock:
      polling_intensity: 1

## Global config
  device_config_glob:
    "light.ge_12724_3way_dimmer_switch_*":
      refresh_value: true
      delay: 5

### pre-0.39 syntax
#  customize:
### Master Bedroom Chandelier
#    light.ge_12724_3way_dimmer_switch_level_8_0:
#      refresh_value: true
#      delay: 5
### Kitchen Lights
#    light.ge_12724_3way_dimmer_switch_level_33_0:
#      refresh_value: true
#      delay: 5
### Dining Room Chandelier
#    light.ge_12724_3way_dimmer_switch_level_34_0:
#      refresh_value: true
#      delay: 5



#####################################################################
### HTTP CONFIG
#####################################################################
http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  trusted_networks:
    - !secret network_1
    - !secret network_2
    - !secret network_3
    - !secret network_4

#####################################################################
### IOS CONFIG
#####################################################################
ios:
  push_categories:
    - name: Alarm
      identifier: 'ALARM'
      actions:
        - identifier: 'SOUND_ALARM'
          title: 'Sound Alarm'
          activationMode: 'background'
          authenticationRequired: yes
          destructive: yes
          behavior: 'default'
          context: 'default'
        - identifier: 'SILENCE_ALARM'
          title: 'Silence Alarm'
          activationMode: 'background'
          authenticationRequired: yes
          destructive: no
          behavior: 'TextInput'
          context: 'default'
          textInputButtonTitle: 'Acknowledge'
          textInputPlaceholder: '...'
  
####################################################
#                                                  #
#                     Includes                 #
#                                                  #
####################################################
alexa: !include alexa.yaml
automation: !include_dir_merge_list automation/
camera: !include cameras.yaml
device_tracker: !include device_trackers.yaml
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_slider: !include input_slider.yaml
light: !include lights.yaml
media_player: !include media_players.yaml
notify: !include notify.yaml
proximity: !include proximity.yaml
scene: !include_dir_merge_list scenes/
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensors/
switch: !include switches.yaml
#tts: !include tts.yaml

#panel_iframe: !include iframe.yaml
#emulated_hue: !include emulated_hue.yaml
#binary_sensor: !include binary_sensors.yaml
#alarm_control_panel: !include alarm_control_panel.yaml
#shell_command: !include shell_commands.yaml

####################################################
#                                                  #
#                     Enables                 #
#                                                  #
####################################################
updater:
sun:
conversation:
frontend:
#discovery:

#####################################################################
### LOGGER
#####################################################################

logger:
  default: error
  logs:
#    homeassistant.components.device_tracker: debug
    homeassistant.components.camera: critical
#    homeassistant.components.group: debug
    homeassistant.components.sensor: critical
#    homeassistant.components.media_player: debug
    homeassistant.components.switch: debug
    homeassistant.components.automation: debug
#    homeassistant.components.notify: debug
#    homeassistant.components.script: debug
#    homeassistant.components.scene: debug

#####################################################################
### RECORDER
#####################################################################

recorder:
  purge_days: 3
  exclude:
    domains:
      - camera
      - sensor
      - media_player
      - notify

#    entities:

#####################################################################
### HISTORY
#####################################################################

history:
  exclude:
    domains:
      - camera
      - climate
      - device_tracker
      - input_boolean
      - input_select
      - input_slider
      - media_player
      - sensor
      - zwave



#    entities:

#####################################################################
### LOGBOOK
#####################################################################

logbook:
  exclude:
    domains:
      - camera
      - media_player

    entities:
      - binary_sensor.fibaro_system_fgms001_motion_sensor_sensor_22_0
      - sensor.fibaro_system_fgms001_motion_sensor_burglar_22_10
      - sensor.fibaro_system_fgms001_motion_sensor_general_22_0
      - sensor.fibaro_system_fgms001_motion_sensor_alarm_level_22_1
      - sensor.fibaro_system_fgms001_motion_sensor_alarm_type_22_0
      - sensor.fibaro_system_fgms001_motion_sensor_seismic_intensity_22_25
      - sensor.fibaro_system_fgms001_motion_sensor_sourcenodeid_22_2
      - sensor.fibaro_system_fgms001_motion_sensor_luminance_22_3
      - sensor.fibaro_system_fgms001_motion_sensor_temperature_22_1
      - sensor.last_boot
      - sensor.date__time
      - sensor.megs_eta
      - sensor.ricks_eta
      - sensor.megs_eta_home
      - sensor.rick_eta_home
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_nearest_storm_distance
#      - sensor.pws_weather
      - sensor.pws_temp_f
      - sensor.pws_feelslike_string
      - sensor.pws_precip_today_string
      - sensor.pws_wind_string
      - sensor.pws_wind_dir
      - sensor.pws_heat_index_string
      - sensor.pws_relative_humidity
      - sensor.pws_dewpoint_string
      - sensor.pws_pressure_in
      - sensor.pws_pressure_mb
      - sensor.pws_solarradiation
      - sensor.pws_uv
      - sensor.pws_observation_time
      - sensor.pws_visibility_mi
      - sensor.peak_hours_status
#      - automation.persistence_publish
      - automation.random_flux_rgb
      - automation.rgb_blue
      - automation.rgb_cool
      - automation.rgb_cyan
      - automation.rgb_green
      - automation.rgb_off
      - automation.rgb_pink
      - automation.rgb_red
      - automation.rgb_violet
      - automation.rgb_yellow

## the complete list of domains ##
#      - automation
#      - climate
#      - conversation
#      - device_tracker
#      - group
#      - homeassistant
#      - ifttt
#      - input_boolean
#      - input_select
#      - input_slider
#      - light
#      - lock
#      - logbook
#      - media_player
#      - mqtt
#      - notify
#      - persistent_notification
#      - scene
#      - script
#      - sensor
#      - switch
#      - zwave