
#####################################################################
### HVAC Upstairs
#####################################################################

## Median Temperature Upstairs
- platform: statistics
  entity_id: sensor.2gig_technologies_ct101_thermostat_iris_temperature_24_1
  name: Upstairs Thermostat Statistics

- platform: template
  sensors:
    ## Upstairs Thermostat Mode
    hvac_upstairs_mode:
      friendly_name: "Upstairs Thermostat Mode"
      # This automatically returns "unknown" if the state is not set
      value_template: "{{ states('climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2') }}"

    ## Upstairs Fan State
    hvac_upstairs_fan:
      friendly_name: "Upstairs HVAC Fan"
      value_template: "{{ (states.climate['2gig_technologies_ct101_thermostat_iris_cooling_1_24_2'].attributes|default({})).fan_state|default('unknown') }}"

    ## Upstairs AC Temp Setpoint
    hvac_upstairs_ac_setpoint:
      friendly_name: "Upstairs AC Setpoint"
      value_template: "{{ (states.climate['2gig_technologies_ct101_thermostat_iris_cooling_1_24_2'].attributes|default({})).temperature|default('unknown') }}"

    ## Upstairs Heat Temp Setpoint
    hvac_upstairs_heat_setpoint:
      friendly_name: "Upstairs Heat Setpoint"
      value_template: "{{ (states.climate['2gig_technologies_ct101_thermostat_iris_heating_1_24_1'].attributes|default({})).temperature|default('unknown') }}"

    ## Upstairs Climate
    hvac_upstairs_climate:
      friendly_name: "Upstairs Climate"
      # This would be a really good use case for macros... :(
      value_template: >-

        {% set temp_entity = 'sensor.2gig_technologies_ct101_thermostat_iris_temperature_24_1' %}
        {% set temp = states(temp_entity)|float(none) %}
        {% set temp_min = states.input_slider.comfort_min.state|default(68.5)|float %}
        {% set temp_max = states.input_slider.comfort_hax.state|default(83.5)|float %}

        {% if temp is none %}
          {{ states(temp_entity) }}
        {% elif temp < temp_min %}

          Cold
        {% elif temp > temp_max %}
          Hot
        {% else %}
          Comfy
        {% endif %}
