
#####################################################################
### HVAC Upstairs
#####################################################################

## Median Temperature Upstairs
- platform: statistics
  entity_id: sensor.2gig_technologies_ct101_thermostat_iris_temperature_24_1
  name: Upstairs Thermostat Statistics

## Upstairs Thermostat Mode
- platform: template
  sensors:
    hvac_upstairs_mode:
      friendly_name: "Upstairs Thermostat Mode"
      value_template: >-
        {%- if states('climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2') != None -%}
          {{ states('climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2') }}
        {%- else -%}
          Unknown
        {%- endif -%}

- platform: template
  sensors:
    hvac_upstairs_fan:
      friendly_name: "Upstairs HVAC Fan"
      value_template: >-
        {%- if states.climate['2gig_technologies_ct101_thermostat_iris_cooling_1_24_2'].attributes.fan_state != None -%}
          {{ states.climate['2gig_technologies_ct101_thermostat_iris_cooling_1_24_2'].attributes.fan_state }}
        {%- else -%}
          Unknown
        {%- endif -%}

## Upstairs AC Temp Setpoint
- platform: template
  sensors:
    hvac_upstairs_ac_setpoint:
      friendly_name: "Upstairs AC Setpoint"
      value_template: >-
        {%- if states.climate['2gig_technologies_ct101_thermostat_iris_cooling_1_24_2'].attributes.temperature != None -%}
          {{ states.climate['2gig_technologies_ct101_thermostat_iris_cooling_1_24_2'].attributes.temperature }}
        {%- else -%}
          Unknown
        {%- endif -%}

## Upstairs Heat Temp Setpoint
- platform: template
  sensors:
    hvac_upstairs_heat_setpoint:
      friendly_name: "Upstairs Heat Setpoint"
      value_template: >-
        {%- if states.climate['2gig_technologies_ct101_thermostat_iris_heating_1_24_1'].attributes.temperature != None -%}
          {{ states.climate['2gig_technologies_ct101_thermostat_iris_heating_1_24_1'].attributes.temperature }}
        {%- else -%}
          Unknown
        {%- endif -%}

## Upstairs Climate
- platform: template
  sensors:
    hvac_upstairs_climate:
      value_template: >-
        {%- if states.sensor['2gig_technologies_ct101_thermostat_iris_temperature_24_1'].state == None -%}
            Unknown
        {%- elif 68.5 <= states.sensor['2gig_technologies_ct101_thermostat_iris_temperature_24_1'].state|float <= 83.5 -%}
            Comfy
        {%- elif states("sensor.2gig_technologies_ct101_thermostat_iris_temperature_24_1") | float < 68.5 -%}
          Cold
        {%- elif states("sensor.2gig_technologies_ct101_thermostat_iris_temperature_24_1") | float > 83.5 -%}
          Hot
        {%- else -%}
            states.sensor['2gig_technologies_ct101_thermostat_iris_temperature_24_1'].state
        {%- endif %}
      friendly_name: "Upstairs Climate"