## Seasons
- platform: template
  sensors:
    season:
      value_template: >-
        {%- if 70 <= states('sensor.pws_temp_f') | float <= 83 -%}
            Awesome
          {%- elif states('sensor.pws_temp_f') | float < 70 -%}
            Winter
          {%- elif states('sensor.pws_temp_f') | float > 83 -%}
            Summer
        {%- else -%}
            {{ states('sensor.pws_temp_f') }}
        {%- endif %}
      friendly_name: "Season"

### old values (working but trying to remover "undefined error"
#        {%- if 70 <= states.sensor.pws_temp_f.state | float <= 83 -%}
#            Awesome
#          {%- elif states.sensor.pws_temp_f.state | float < 70 -%}
#            Winter
#          {%- elif states.sensor.pws_temp_f.state | float > 83 -%}
#            Summer
#        {%- else -%}
#            {{ states.sensor.pws_temp_f.state }}
#        {%- endif %}