## Seasons
- platform: template
  sensors:
    season:
      friendly_name: "Season"
      # @dale3h: Added optional input_slider to set temperature thresholds
      value_template: >-
        {% set temp_entity = 'sensor.pws_temp_f' %}
        {% set temp = states(temp_entity)|float(none) %}
        {% set temp_min = states.input_slider.season_winter.state|default(70)|float %}
        {% set temp_max = states.input_slider.season_summer.state|default(83)|float %}
        
        {% if temp is none %}
          {{ states(temp_entity) }}
        {% elif temp < temp_min %}
          Winter
        {% elif temp > temp_max %}
          Summer
        {% else %}
          Awesome
        {% endif %}
