#####################################################################
### Broadlink RM Pro
#####################################################################

- platform: broadlink
  host: !secret broadlink_ip
  mac: !secret broadlink_mac
  monitored_conditions:
    - 'temperature'