
#####################################################################
### WEATHER
#####################################################################

- platform: moon

# sensor: weather - WUnderground
- platform: wunderground
  api_key: !secret wu_api_key
#  pws_id: !secret pws_id_key
  monitored_conditions:
    - weather
    - alerts
    - temp_f
    - station_id
    - feelslike_f
    - feelslike_string
    - heat_index_f
    - heat_index_string
    - dewpoint_f
    - dewpoint_string
    - wind_mph
    - UV
    - pressure_in
    - pressure_mb
    - wind_dir
    - wind_string
    - relative_humidity
    - visibility_mi
    - precip_today_in
    - precip_today_string
    - solarradiation
    - observation_time

# sensor: weather - darksky
- platform: darksky
  api_key: !secret forecast_api_key
  monitored_conditions:
    - nearest_storm_distance
    - cloud_cover
    - daily_summary
    - precip_intensity
    - precip_probability
    - precip_intensity_max
