#####################################################################
### HEAT - Upstairs Limit Reached
#####################################################################

- alias: heat upstairs if too cold
  trigger:
    - platform: template
      value_template: "{{ states.sensor['2gig_technologies_ct101_thermostat_iris_temperature_24_1'].state < '66' }}"

# kick the heat on for 3 hours
  action:
    - service: script.heat_upstairs_180min

#####################################################################
### HEAT - Upstairs trigger on temperature
#####################################################################

- alias: upstairs heating triggered
  trigger:
    - platform: template
      value_template: "{{ states.sensor['2gig_technologies_ct101_thermostat_iris_temperature_24_1'].state < '69' }}"

  condition:
    - condition: state
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2
      state: 'Heat'

    - condition: state
      entity_id: sensor.hvac_upstairs_climate
      state: 'Cold'

    - condition: state
      entity_id: script.heat_upstairs_180min
      state: 'off'

    - condition: state
      entity_id: input_boolean.peak_hours
      state: 'off'

    - condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'on'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

# kick the heat on for 3 hours
  action:
    - service: script.heat_upstairs_180min

#####################################################################
### HEAT - Upstairs Weekday Mornings
#####################################################################

- alias: upstairs heating weekday mornings
  trigger:
    - platform: time
      after: '03:44:59'

  condition:
    - condition: state
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2
      state: 'Heat'

    - condition: state
      entity_id: sensor.hvac_upstairs_climate
      state: 'Cold'

    - condition: state
      entity_id: script.heat_upstairs_180min
      state: 'off'

    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri

    - condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'on'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

# kick the heat on for 3 hours
  action:
    - service: script.heat_upstairs_180min

#####################################################################
### HEAT - Upstairs Weekday Nights
#####################################################################

- alias: upstairs heating weekday night
  trigger:
    - platform: time
      after: '20:44:59'

  condition:
    - condition: state
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2
      state: 'Heat'

    - condition: state
      entity_id: sensor.hvac_upstairs_climate
      state: 'Cold'

    - condition: state
      entity_id: script.heat_upstairs_180min
      state: 'off'

    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - sun

    - condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'on'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

# kick the heat on for 3 hours
  action:
    - service: script.heat_upstairs_180min

#####################################################################
### HEAT - Upstairs Weekends
#####################################################################

- alias: upstairs heating weekend nights
  trigger:

    - platform: time
      after: '21:59:59'

  condition:
    - condition: state
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2
      state: 'Heat'

    - condition: state
      entity_id: sensor.hvac_upstairs_climate
      state: 'Cold'

    - condition: state
      entity_id: script.heat_upstairs_180min
      state: 'off'

    - condition: time
      weekday:
      - fri
      - sat

    - condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'on'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

# kick the heat on for 3 hours
  action:
    - service: script.heat_upstairs_180min

#####################################################################
### HEAT - Upstairs Weekend Mornings
#####################################################################

- alias: upstairs heating weekend mornings
  trigger:

    - platform: time
      after: '06:59:59'

  condition:
    - condition: state
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_cooling_1_24_2
      state: 'Heat'

    - condition: state
      entity_id: sensor.hvac_upstairs_climate
      state: 'Cold'

    - condition: state
      entity_id: script.heat_upstairs_180min
      state: 'off'

    - condition: time
      weekday:
      - sat
      - sun

    - condition: or
      conditions:
        - condition: state
          entity_id: group.family
          state: 'on'

        - condition: state
          entity_id: input_boolean.visitor_mode
          state: 'on'

# kick the heat on for 3 hours
  action:
    - service: script.heat_upstairs_180min