#####################################################################
### Set the Living Room Normal Scene (if home)
#####################################################################

- alias: turn on living room scene after sunset
  hide_entity: True
  trigger:
    - platform: sun
      event: sunset
      offset: '00:15:00'

  condition:
    - condition: state
      entity_id: group.family
      state: 'on'

  action:
    - service: scene.turn_on
      entity_id: scene.living_room_normal

#####################################################################
### Turn off the lights if the sun is up
#####################################################################

- alias: turn off lights at sun up
  hide_entity: True
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      above: 1.75

  condition:
    - condition: time
      after: '04:00:00'
      before: '10:00:00'

  action:
    - service: light.turn_off

    - service: switch.turn_off


#####################################################################
### Turn on some lights when we get home
#####################################################################

- alias: turn on lights upon arrival
  trigger:
    platform: state
    entity_id: group.family
    from: 'off'
    to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

  action:
# notify Chrome
    - service: notify.notify
      data:
        title: "Welcome Home"
        target: "device/Chrome"
        message: "Turning on some lights"
# notify iOS
    - service: notify.ios_iphwn666
      data:
        title: "Welcome Home"
        message: "Turning on some lights"
        data:
          push:
            sound: "US-EN-Alexa-Welcome-Home.wav"

    - service: scene.turn_on
      entity_id: scene.living_room_bright

    - delay:
        minutes: 5

    - service: scene.turn_on
      entity_id: scene.living_room_normal

#####################################################################
### Set the Living Room Cloudy Scene (if home)
#####################################################################

- alias: turn on living room scene if cloudy
  hide_entity: True
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 20.0

    - platform: numeric_state
      entity_id: sensor.dark_sky_cloud_coverage
      above: 90

    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_intensity
      above: 1

  condition:
    - condition: state
      entity_id: group.family
      state: 'on'

    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: numeric_state
              entity_id: sun.sun
              value_template: '{{ state.attributes.elevation }}'
              below: 20.0
            - condition: numeric_state
              entity_id: sensor.dark_sky_cloud_coverage
              above: 90
        - condition: numeric_state
          entity_id: sensor.dark_sky_precip_intensity
          above: 1

  action:
    - service: scene.turn_on
      entity_id: scene.living_room_cloudy

#####################################################################
### Turn off the lights when rain has stopped
#####################################################################

- alias: rain has stopped
  hide_entity: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_intensity
      below: 1

  action:
    - service: homeassistant.turn_off
      entity_id: group.living_room

    - service: homeassistant.turn_off
      entity_id: group.entry_lighting