#####################################################################
### Turn on the porch lights
#####################################################################

- alias: porch lights on at sunset
  hide_entity: True
  trigger:
    - platform: sun
      event: sunset
      offset: '00:10:00'

  action:
    - service: homeassistant.turn_on
      entity_id: group.porch

#####################################################################
### Turn off the porch lights
#####################################################################

- alias: porch lights off at sunrise
  hide_entity: True
  trigger:
    - platform: sun
      event: sunrise
      offset: '-00:15:00'

  action:
    - service: homeassistant.turn_off
      entity_id: group.porch

#####################################################################
### Turn on the Christmas Lights - (GE plugin outlet)
#####################################################################

## Turn on Christmas lights
#    - service: switch.turn_on
#      entity_id: switch.ge_unknown_type4f50_id3031_switch_23_0