#####################################################################
### Change Fan speed on input_select
#####################################################################

- alias: living room fan speed selector
  trigger:
    - platform: state
      entity_id: input_select.living_room_fan_speed

  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state != 'Select an option...' }}"

  action:
    # Turn the corresponding switch on to send the fan speed command
    - service: switch.turn_on
      data_template:
        entity_id: "switch.living_room_fan_{{ trigger.to_state.state|lower|replace(' ', '_') }}"

    # Reset the Input Select to "Select an option..."
    - service: input_select.select_option
      data_template:
        entity_id: "{{ trigger.to_state.entity_id }}"
        option: Select an option...