######################################################################
#### Master Bedroom Fan Speed
######################################################################

- alias: master_bedroom_fan_speed_selector
  trigger:
    - platform: state
      entity_id: input_select.master_bedroom_fan_speed

  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state != 'Select an option...' }}"

  action:
    # Turn the corresponding switch on to send the fan speed command
    - service: switch.turn_on
      data_template:
        entity_id: "switch.master_bedroom_fan_{{ trigger.to_state.state|lower|replace(' ', '_') }}"

    # Reset the Input Select to "Select an option..."
    - service: input_select.select_option
      data_template:
        entity_id: "{{ trigger.to_state.entity_id }}"
        option: Select an option...

######################################################################
#### Master Bedroom Fan Options
######################################################################

- alias: master_bedroom_fan_option_selector
  trigger:
    - platform: state
      entity_id: input_select.master_bedroom_fan_options

  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state != 'Select an option...' }}"

  action:
    # Turn the corresponding switch on to send the fan speed command
    - service: switch.turn_on
      data_template:
        entity_id: "switch.master_bedroom_fan_{{ trigger.to_state.state|lower|replace(' ', '_') }}"

    # Reset the Input Select to "Select an option..."
    - service: input_select.select_option
      data_template:
        entity_id: "{{ trigger.to_state.entity_id }}"
        option: Select an option...