#####################################################################
### Unlock door for Megs
#####################################################################

- alias: unlock door for megs
  trigger:
    - platform: state
      entity_id: input_boolean.megs_home
      from: 'off'
      to: 'on'

# door should be locked
  condition:
    - condition: template
      value_template: "{{ states.lock.assa_abloy_yale_real_living_captouch_lever_locked_16_0.state == 'locked' }}"

# unlock the south door for Megs
  action:
    - service: script.unlock_megs